### ISSUE TITLE
Subtask object has no attribute command_name

### ISSUE THREAD

**Issue by arkenoi** [coddingtonbear/taskwarrior-subtask-capsule#4]
▲ ~ tw add foo                                                                                                                                            
Created task 8.

 ▲ ~ tw 8 subtask bar                                                                                                                                      
Traceback (most recent call last):
  File "/usr/bin/tw", line 11, in <module>
    load_entry_point('taskwarrior-capsules==0.3.2', 'console_scripts', 'tw')()
  File "/usr/lib/python2.7/site-packages/taskwarrior_capsules/cmdline.py", line 107, in main
    terminal=term,
  File "/usr/lib/python2.7/site-packages/taskwarrior_capsules/capsule.py", line 159, in execute
    self.validate(**kwargs)
  File "/usr/lib/python2.7/site-packages/taskwarrior_capsules/capsule.py", line 76, in validate
    self.command_name,
AttributeError: 'Subtask' object has no attribute 'command_name'

 △ ~

**Comment by nh-3** [comment]
Same here

Traceback (most recent call last):
  File "/usr/local/bin/tw", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/taskwarrior_capsules/cmdline.py", line 107, in main
    terminal=term,
  File "/usr/local/lib/python2.7/dist-packages/taskwarrior_capsules/capsule.py", line 159, in execute
    self.validate(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/taskwarrior_capsules/capsule.py", line 76, in validate
    self.command_name,
AttributeError: 'Subtask' object has no attribute 'command_name'

**Comment by hancerli** [comment]
Yep yep +1

```
Traceback (most recent call last):
  File "/home/burak/.local/bin/tw", line 11, in <module>
    sys.exit(main())
  File "/home/burak/.local/lib/python2.7/site-packages/taskwarrior_capsules/cmdline.py", line 107, in main
    terminal=term,
  File "/home/burak/.local/lib/python2.7/site-packages/taskwarrior_capsules/capsule.py", line 159, in execute
    self.validate(**kwargs)
  File "/home/burak/.local/lib/python2.7/site-packages/taskwarrior_capsules/capsule.py", line 76, in validate
    self.command_name,
AttributeError: 'Subtask' object has no attribute 'command_name'

```

**Comment by mokrunka** [comment]
Hi @haniawni, I am the new owner of the taskwarrior capsules repo (and several associated repos, including this one). I have at long last merged your PR, and bumped taskwarrior-subtask-capsule to version 0.2.5 in PyPI.
